apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: giri1492/backend:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
   

    #Kubse ns cli tool to shortctu for - n expense( naming namespace again and again)
    # this is comi=unication between backend to mysql no need to expose services so putting cluterip